export const SET_GLOBAL_MESSAGE = 'SET_GLOBAL_MESSAGE';
export const UNSET_GLOBAL_MESSAGE = 'UNSET_GLOBAL_MESSAGE';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_RESET = 'AUTH_RESET';
